version: "3.7"
services:
  nestserver:
    build: ./
    ports:
      - "3000:3000"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"